# Generated by Django 2.2 on 2021-05-04 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('contest_type', models.CharField(default='', max_length=20)),
                ('start', models.DateTimeField(verbose_name='date-published')),
                ('end', models.DateTimeField(default='', verbose_name='date-published')),
                ('description', models.TextField(default='')),
                ('status', models.CharField(default='active', max_length=20)),
                ('participant', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='temp', max_length=50)),
                ('solved', models.IntegerField(default=0)),
                ('time_limit', models.IntegerField(default=0)),
                ('memory_limit', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('input', models.TextField(default='')),
                ('output', models.TextField(default='')),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplyExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exercise', models.CharField(default='temple', max_length=20)),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('exercise', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Exercise_post_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contests.Exercise')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
