# Generated by Django 2.2 on 2021-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
